version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: belka1/foodgram-backend:latest
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  frontend:
    image: belka1/foodgram-frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"

    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
      
      - static_value:/var/html/static/

      - media_value:/var/html/media/

      - ../frontend/build:/usr/share/nginx/html/

      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  db_data:
  static_value:
  media_value: