version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"

    volumes:
      - static_value:/var/html/static/

      - media_value:/var/html/media/

      - ./nginx.conf:/etc/nginx/conf.d/default.conf

      - ../frontend/build:/usr/share/nginx/html/

      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - frontend
      - backend
    restart: always


volumes:
  static_value:
  media_value:
  db_data: